### ISSUE TITLE
Repository search not working

### ISSUE THREAD

**Issue by ghost** [ocaml-opam/opam2web#153]
*Initially reported at https://github.com/ocaml/opam/issues/2986 , where it was requested that this issue be reported here instead.*

### Steps to reproduce

1. Go to https://opam.ocaml.org/packages/ in a browser that does not use JavaScript, or has JavaScript disabled.
1. In the "Search packages" field near the top-right of the page, enter a string to search for, e.g. "rdf" (without quote marks).
1. Press <key>Rtn</key>.

### Expected outcome

A list of search results would be presented, which would at least include a link to https://opam.ocaml.org/packages/rdf/ .

### Actual outcome

The page refreshes, emptying the "Search packages" field.

**Comment by kanishka-work** [comment]
This appears fixed currently

**Comment by dra27** [comment]
@kanishka-work - this is not fixed (I don't think it's that likely to be, either)

**Comment by kanishka-work** [comment]
sorry, misread the js disabled when I performed the test

**Comment by AltGr** [comment]
Well, this is a static website, so that feature is not expected to work. However, there should certainly be a nicer fallback than displaying the field and reloading the page.
I would advise the following workarounds:
- use your browser search: the results are displayed on a single page, so that should be fairly straightforward if you don't need to search within the long descriptions
- use the `opam search` command
